# Generated by Django 2.2.6 on 2020-09-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='gallery/static/images/no-img.jpg', height_field='image_height', upload_to='gallery', width_field='image_width')),
                ('name', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
            ],
        ),
    ]
