# Generated by Django 2.2.6 on 2020-09-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='gallery/no-img.jpg', height_field='image_height', upload_to='gallery', width_field='image_width'),
        ),
    ]
