# Generated by Django 2.2.6 on 2020-09-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200902_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='gallery/no-img.jpg', upload_to='gallery'),
        ),
    ]
