# Generated by Django 2.2.6 on 2020-10-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200902_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='details',
            field=models.CharField(default='Color base agua sobre poliester', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='disp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.CharField(default='60x42 cm', max_length=200),
            preserve_default=False,
        ),
    ]
