# Generated by Django 2.2.6 on 2020-11-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20201025_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Bloque', 'verbose_name_plural': 'Bloques'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
        migrations.AlterField(
            model_name='image',
            name='details',
            field=models.CharField(max_length=200, verbose_name='Materiales/Técnica'),
        ),
        migrations.AlterField(
            model_name='image',
            name='disp',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='gallery/no-img.jpg', upload_to='gallery', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.CharField(max_length=200, verbose_name='Dimensiones'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Album', verbose_name='Bloque'),
        ),
    ]
