# Generated by Django 2.2.6 on 2020-11-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20201120_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='gallery/no-img.jpg', upload_to='gallery', verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
